nhs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from search import views
from nurse import views as nurseviews

from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    #API ABove
    #path('nurses/', nurseviews.NurseList.as_view()),
    path('api/<str:postcode>', nurseviews.PostCodeToNurse.as_view()),
    #API
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('nurse/', include('nurse.urls')),
]

#urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nurse/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
   path('<int:nurse_id>/', views.detail, name='detail'),
]

search/urls.py
from django.urls import path,include

from . import views 

urlpatterns = [
   path('', views.HomePageView.as_view(), name='home'),
   path('about/', views.About.as_view(), name='about'),
   path('search/', views.SearchResultsView.as_view(), name='search_results'),
   path('sign-up/', views.SignUp.as_view(), name='sign up'),
   path('contact/', views.Contact.as_view(), name='contact'),
]

nurse/models.py
from django.db import models
import json
import requests
from django.http import Http404

# Create your models here.


class Nurse(models.Model):
    firstName = models.CharField(
        max_length=100, default="", verbose_name="First Name")
    lastName = models.CharField(
        max_length=100, default="", verbose_name="Last Name")
    teamName = models.CharField(
        max_length=100, default="", verbose_name="Team Name")
    districtNurseBorough = models.CharField(
        max_length=100, default="", verbose_name="District Nursing Borough")
    postCode = models.CharField(
        max_length=10, default="", verbose_name="Postal code")
    phoneNumber = models.CharField(max_length=20, verbose_name="Phone Number")
    email = models.EmailField(max_length=100, null=True)
    latitude = models.FloatField(max_length=10, default=0)
    longitude = models.FloatField(max_length=10, default=0)
    primary_care_trust = models.CharField(max_length=100, default="N/A")
    addressLine1 = models.CharField(max_length=100, default="N/A")
    addressLine2 = models.CharField(max_length=100, default="N/A")

    def save(self, *args, **kwargs):
        data = self.getAreaData(self.postCode)
        self.latitude = data[0]
        self.longitude = data[1]
        self.primary_care_trust = data[2]
        super().save(self, *args, **kwargs)

    def __str__(self):
        return self.firstName + " " + self.lastName

    def getAreaData(self, postcode):
        try:
            response = requests.get(
                "https://api.postcodes.io/postcodes/" + str(postcode))
            data = response.json()
            lat = data['result']['latitude']
            longitude = data['result']['longitude']
            primarycaretrust = data['result']['primary_care_trust']
            return (lat, longitude, primarycaretrust)
        except KeyError:
            raise Http404


class PDFFile(models.Model):
    pdffile = models.FileField(null=True, blank=True)
    nurse = models.ForeignKey(
        Nurse, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "File for " + self.nurse.primary_care_trust + " area"

search/models.py
from django.db import models

# Create your models here.

nurse/forms.py
from django import forms

class NewNurseForm(forms.Form):
    firstName = forms.CharField(label="First Name", max_length=100)
    lastName = forms.CharField(label="Last Name", max_length=100)
    postcode = forms.CharField(label="Post Code", max_length=10)
    phoneNumber = forms.CharField(label="Phone Number", max_length=20)
    email = forms.EmailField(label="Email", max_length=50)

nurse/views.py
from django.shortcuts import render, get_object_or_404
from .models import Nurse

from rest_framework import viewsets
from rest_framework import permissions
from .serializers import NurseSerializer

from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.renderers import JSONRenderer
# Create your views here.

def detail(request, nurse_id):
    nurse = get_object_or_404(Nurse, pk=nurse_id)
    return render(request, 'nurse/more-info.html', {'nurse': nurse})

class NurseList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request, format=None):
        nurses = Nurse.objects.all()
        serializer = NurseSerializer(nurses, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        nurse = NurseSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class PostCodeToNurse(APIView):
    renderer_classes = [JSONRenderer]

    def get_nurse(self, postcode):
        try:
            return Nurse.objects.get(primary_care_trust=Nurse.getAreaData(self, postcode)[2])
        except Nurse.DoesNotExist:
            raise Http404
    
    def get(self, request, postcode, format=None):
        nurse = self.get_nurse(postcode)
        serializer = NurseSerializer(nurse)
        return Response(serializer.data)

search/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.views.generic import TemplateView, ListView
from django.db.models import Q

from nurse.models import Nurse

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions


# Create your views here.

class HomePageView(TemplateView):
    template_name = "search/index.html"

class SearchResultsView(ListView):
    model = Nurse
    template_name = 'search/search-results.html'
    

    def get_queryset(self): # new
        q = self.request.GET.get('q')
        #Turns the postcode to an area ie. SE17xb returns Lambeth
        lat,lng, area = Nurse.getAreaData(self, q)
        object_list = Nurse.objects.filter(
            Q(primary_care_trust__icontains=area)
        )

        return object_list
        
class Test(TemplateView):
    template_name = "search/test.html"

class About(TemplateView):
    template_name = "search/about.html"

class SignUp(TemplateView):
    template_name = "search/sign-up.html"

class Contact(TemplateView):
    template_name = "search/contact.html"

nurse/templates/nurse/more-info.html
{% load static %}
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Sat Apr 11 2020 17:52:46 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5e91b01206600fc63ccfba28" data-wf-site="5e90ec5e37cf8d94ec380082">
<head>
  </style>

  <meta charset="utf-8">
  <title>More Info</title>
  <meta content="More Info" property="og:title">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href=" /static/search/css/normalize.css" rel="stylesheet" type="text/css">
  <link href="/static/search/css/webflow.css" rel="stylesheet " type="text/css">
  <link href="/static/search/css/find-my-nurse.webflow.css" rel="stylesheet" type="text/css">
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="images/webclip.png" rel="apple-touch-icon">
</head>
<body class="body more-info-page">
  <div class="nav-container">
    <div style="display:none;-webkit-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="nav-wrapper">
      <div class="navbar-fmn-text">Find My Nurse.</div>
      <div class="nav-links-wrapper"><a href="/" class="link">Home</a><a href="/about" aria-current="page" class="link w--current">About</a><a href="/contact" class="link">Contact</a><a href="/sign-up" class="link">Register</a></div>
      <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cc3" style="-webkit-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="navbar-close-button">
        <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cc4" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
      <div class="navbar-close-button mobile">
        <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cc6" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
    </div>
    <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cc7" class="hamburger-icon-button more-info-page">
      <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cc8" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
    <div class="hamburger-icon-button mobile">
      <div data-w-id="b6bc05ff-a4ce-4d3f-0d91-1eb4b6167cca" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
  </div>
  <div class="more-info-container">
    <div class="information-container"><a href="javascript:window.history.go(-1)" class="back-button-container w-inline-block"><img src="images/Arrow_Icon.svg" alt="" class="arrow-icon"></a>
      <div class="information-wrapper">
        <div class="nurse-name-text">{{ nurse.firstName }} {{ nurse.lastName }}</div>
        <div class="details-text email">{{ nurse.email }}</div>
        <div class="details-text number">{{ nurse.phoneNumber }}</div>
        <div class="details-text address-line-1">Address: </div>
        <div class="details-text address-line-1">{{ nurse.addressLine1 }}</div>
        <div class="details-text post-code">{{ nurse.addressLine2 }}</div>
        <div class="details-text post-code">{{ nurse.postCode }}</div>
        <div class="details-text address-line-1">Files: 
          {% for file in nurse.pdffile_set.all %} 
        <a href="{{ file.pdffile.url }}/">{{ file.pk }}</a>,
          {% endfor %}
        </div>
        
      </div><a href="#" class="details-text map-link">Open in maps</a></div>
    <div class="map-container">
      <img style="height: 100%; width: 100%; object-fit: cover;"src="https://maps.googleapis.com/maps/api/staticmap?center={{nurse.latitude}},{{nurse.longitude}}&markers=color:red%7Clabel:N%7C{{nurse.latitude}},{{nurse.longitude}}&size=1024x768&zoom=12&key=AIzaSyAzdtaiHfUOkBmCAvhdZ65hemgp8Fow8HM">
    </div>

  </div>

  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5e90ec5e37cf8d94ec380082" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  <script src="/static/search/js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

search/templates/search/about.html
{% load static %}
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Sat Apr 11 2020 17:52:46 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5e91b04e37cf8db4603bf375" data-wf-site="5e90ec5e37cf8d94ec380082">
<head>
  <meta charset="utf-8">
  <title>About</title>
  <meta content="About" property="og:title">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href=" {% static 'search/css/normalize.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'search/css/webflow.css' %}" rel="stylesheet " type="text/css">
  <link href=" {% static 'search/css/find-my-nurse.webflow.css' %} " rel="stylesheet" type="text/css">
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="images/webclip.png" rel="apple-touch-icon">
</head>
<body class="body">
  <div class="nav-container">
    <div style="display:none;-webkit-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="nav-wrapper">
      <div class="navbar-fmn-text">Find My Nurse.</div>
      <div class="nav-links-wrapper"><a href="/" class="link">Home</a><a href="/about" aria-current="page" class="link w--current">About</a><a href="/contact" class="link">Contact</a><a href="/sign-up" class="link">Register</a></div>
      <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234db" style="-webkit-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="navbar-close-button">
        <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234dc" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
      <div class="navbar-close-button mobile">
        <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234de" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
    </div>
    <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234df" class="hamburger-icon-button">
      <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234e0" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
    <div class="hamburger-icon-button mobile">
      <div data-w-id="bb864af3-79ec-0a04-c0ed-6bd1918234e2" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
  </div>
  <div class="container vertical">
    <div class="heading-text about-page">Find My Nurse</div>
    <div class="paragraph-text">Welcome to Find My Nurse. We are a service that helps members of the public and the National Healthcare Service quickly and easily identify regional nurses. This service has no affiliation with the NHS, and is entirely non-profit and run voluntarily.<br>‍</div><a href="sign-up.html" class="paragraph-text">If you are a nurse and you want to register yourself on the service, click here!</a></div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5e90ec5e37cf8d94ec380082" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="{% static 'search/js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

search/templates/search/contact.html
{% load static %}

<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Sat Apr 11 2020 17:52:46 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5e91b0579610461b8272f829" data-wf-site="5e90ec5e37cf8d94ec380082">
<head>
  <meta charset="utf-8">
  <title>Contact</title>
  <meta content="Contact" property="og:title">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href=" {% static 'search/css/normalize.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'search/css/webflow.css' %}" rel="stylesheet " type="text/css">
  <link href=" {% static 'search/css/find-my-nurse.webflow.css' %} " rel="stylesheet" type="text/css">
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="images/webclip.png" rel="apple-touch-icon">
</head>
<body class="body">
  <div class="nav-container">
    <div style="display:none;-webkit-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, -80PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="nav-wrapper">
      <div class="navbar-fmn-text">Find My Nurse.</div>
      <div class="nav-links-wrapper"><a href="/" class="link">Home</a><a href="/about" aria-current="page" class="link w--current">About</a><a href="/contact" class="link">Contact</a><a href="/sign-up" class="link">Register</a></div>
      <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df98b" style="-webkit-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 0PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="navbar-close-button">
        <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df98c" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
      <div class="navbar-close-button mobile">
        <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df98e" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="100" class="x-icon"></div>
      </div>
    </div>
    <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df98f" class="hamburger-icon-button">
      <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df990" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
    <div class="hamburger-icon-button mobile">
      <div data-w-id="0473c6cd-5be6-9156-765e-919ba66df992" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5e90ec5e37cf8d94ec380082/5e91b39365892b009b0b78ac_Menu_Animated_Button.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-default-duration="0.6339672748119514" data-duration="0" data-ix2-initial-state="0" class="menu-icon"></div>
    </div>
  </div>
  <div class="container vertical">
    <div class="heading-text">Contact</div>
    <div class="paragraph-text">If you have any concerns or feedback, please don&#x27;t hesitate to contact us.</div>
    <div class="contact-text email">Email: martinisiu14@email.com</div>
    <div class="contact-text phone">Phone: +44 7478 595598</div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5e90ec5e37cf8d94ec380082" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="{% static 'search/js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>